// <auto-generated />
using System;
using Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924202827_forgot-password")]
    partial class forgotpassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PsicopedagogoId")
                        .HasColumnType("int");

                    b.HasKey("PersonaId");

                    b.HasIndex("PsicopedagogoId");

                    b.ToTable("Paciente", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Psicopedagogo", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("PersonaId");

                    b.ToTable("Psicopedagogo", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("PsicopedagogoId")
                        .HasColumnType("int");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaExpiracionTokenRestablecimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecuperacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRestablecimiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PsicopedagogoId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Persona", "Persona")
                        .WithOne("Paciente")
                        .HasForeignKey("Backend.Domain.Entities.Paciente", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.Psicopedagogo", "Psicopedagogo")
                        .WithMany("Pacientes")
                        .HasForeignKey("PsicopedagogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Psicopedagogo");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Psicopedagogo", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Persona", "Persona")
                        .WithOne("Psicopedagogo")
                        .HasForeignKey("Backend.Domain.Entities.Psicopedagogo", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Psicopedagogo", "Psicopedagogo")
                        .WithOne("Usuario")
                        .HasForeignKey("Backend.Domain.Entities.Usuario", "PsicopedagogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psicopedagogo");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Paciente")
                        .IsRequired();

                    b.Navigation("Psicopedagogo")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Psicopedagogo", b =>
                {
                    b.Navigation("Pacientes");

                    b.Navigation("Usuario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
