// <auto-generated />
using System;
using Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006222713_TipoDificultad")]
    partial class TipoDificultad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoEjercicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoEjercicioId");

                    b.ToTable("Ejercicio", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Informe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodoDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodoHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("PsicopedagogoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PsicopedagogoId");

                    b.ToTable("Informe", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Intervencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("objetivo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("observaciones")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Intervencion", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.IntervencionTipoDificultad", b =>
                {
                    b.Property<int>("IntervencionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDificultadId")
                        .HasColumnType("int");

                    b.HasKey("IntervencionId", "TipoDificultadId");

                    b.HasIndex("TipoDificultadId");

                    b.ToTable("IntervencionTipoDificultad", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Metrica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoAgregacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unidad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Metrica", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonaId");

                    b.ToTable("Paciente", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Psicopedagogo", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("PersonaId");

                    b.ToTable("Psicopedagogo", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.PsicopedagogoPaciente", b =>
                {
                    b.Property<int>("PsicopedagogoId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntervencionId")
                        .HasColumnType("int");

                    b.HasKey("PsicopedagogoId", "PacienteId");

                    b.HasIndex("IntervencionId")
                        .IsUnique();

                    b.HasIndex("PacienteId");

                    b.ToTable("PsicopedagogoPaciente", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Resultado", b =>
                {
                    b.Property<int>("SesionId")
                        .HasColumnType("int");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("Aciertos")
                        .HasColumnType("int");

                    b.Property<int>("Errores")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TiempoSegundos")
                        .HasColumnType("int");

                    b.HasKey("SesionId", "EjercicioId");

                    b.ToTable("Resultado", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.ResultadoMetrica", b =>
                {
                    b.Property<int>("SesionId")
                        .HasColumnType("int");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("MetricaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SesionId", "EjercicioId", "MetricaId");

                    b.HasIndex("MetricaId");

                    b.ToTable("ResultadoMetrica", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("PsicopedagogoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PsicopedagogoId", "PacienteId");

                    b.ToTable("Sesion", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.SesionEjercicio", b =>
                {
                    b.Property<int>("SesionId")
                        .HasColumnType("int");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.HasKey("SesionId", "EjercicioId");

                    b.HasIndex("EjercicioId");

                    b.ToTable("SesionEjercicio", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.TipoDificultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoDificultad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Dificultades de atención"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Dificultades en lectoescritura"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Dificultades en cálculo"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Dificultades en memoria"
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.TipoEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoEjercicio");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("PsicopedagogoId")
                        .HasColumnType("int");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracionTokenRestablecimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecuperacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRestablecimiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PsicopedagogoId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Ejercicio", b =>
                {
                    b.HasOne("Backend.Domain.Entities.TipoEjercicio", "TipoEjercicio")
                        .WithMany("Ejercicios")
                        .HasForeignKey("TipoEjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEjercicio");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Informe", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.Psicopedagogo", "Psicopedagogo")
                        .WithMany()
                        .HasForeignKey("PsicopedagogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Psicopedagogo");
                });

            modelBuilder.Entity("Backend.Domain.Entities.IntervencionTipoDificultad", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Intervencion", "Intervencion")
                        .WithMany("TiposDificultad")
                        .HasForeignKey("IntervencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.TipoDificultad", "TipoDificultad")
                        .WithMany("IntervencionTiposDificultad")
                        .HasForeignKey("TipoDificultadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervencion");

                    b.Navigation("TipoDificultad");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Persona", "Persona")
                        .WithOne("Paciente")
                        .HasForeignKey("Backend.Domain.Entities.Paciente", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Psicopedagogo", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Persona", "Persona")
                        .WithOne("Psicopedagogo")
                        .HasForeignKey("Backend.Domain.Entities.Psicopedagogo", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Backend.Domain.Entities.PsicopedagogoPaciente", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Intervencion", "Intervencion")
                        .WithOne("PsicopedagogoPaciente")
                        .HasForeignKey("Backend.Domain.Entities.PsicopedagogoPaciente", "IntervencionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.Paciente", "Paciente")
                        .WithMany("PsicopedagogoPacientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.Psicopedagogo", "Psicopedagogo")
                        .WithMany("PsicopedagogoPacientes")
                        .HasForeignKey("PsicopedagogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervencion");

                    b.Navigation("Paciente");

                    b.Navigation("Psicopedagogo");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Resultado", b =>
                {
                    b.HasOne("Backend.Domain.Entities.SesionEjercicio", "SesionEjercicio")
                        .WithOne("Resultado")
                        .HasForeignKey("Backend.Domain.Entities.Resultado", "SesionId", "EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SesionEjercicio");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ResultadoMetrica", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Metrica", "Metrica")
                        .WithMany("ResultadoMetricas")
                        .HasForeignKey("MetricaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.Resultado", "Resultado")
                        .WithMany("ResultadoMetricas")
                        .HasForeignKey("SesionId", "EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metrica");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Sesion", b =>
                {
                    b.HasOne("Backend.Domain.Entities.PsicopedagogoPaciente", "PsicopedagogoPaciente")
                        .WithMany("Sesiones")
                        .HasForeignKey("PsicopedagogoId", "PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PsicopedagogoPaciente");
                });

            modelBuilder.Entity("Backend.Domain.Entities.SesionEjercicio", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Ejercicio", "Ejercicio")
                        .WithMany("SesionEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.Sesion", "Sesion")
                        .WithMany("SesionEjercicios")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Psicopedagogo", "Psicopedagogo")
                        .WithOne("Usuario")
                        .HasForeignKey("Backend.Domain.Entities.Usuario", "PsicopedagogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psicopedagogo");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Ejercicio", b =>
                {
                    b.Navigation("SesionEjercicios");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Intervencion", b =>
                {
                    b.Navigation("PsicopedagogoPaciente");

                    b.Navigation("TiposDificultad");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Metrica", b =>
                {
                    b.Navigation("ResultadoMetricas");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("PsicopedagogoPacientes");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Paciente")
                        .IsRequired();

                    b.Navigation("Psicopedagogo")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Psicopedagogo", b =>
                {
                    b.Navigation("PsicopedagogoPacientes");

                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.PsicopedagogoPaciente", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Resultado", b =>
                {
                    b.Navigation("ResultadoMetricas");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Sesion", b =>
                {
                    b.Navigation("SesionEjercicios");
                });

            modelBuilder.Entity("Backend.Domain.Entities.SesionEjercicio", b =>
                {
                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("Backend.Domain.Entities.TipoDificultad", b =>
                {
                    b.Navigation("IntervencionTiposDificultad");
                });

            modelBuilder.Entity("Backend.Domain.Entities.TipoEjercicio", b =>
                {
                    b.Navigation("Ejercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
